;
; File generated by cc65 v 2.18 - Git f8be35b4
;
	.fopt		compiler,"cc65 v 2.18 - Git f8be35b4"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "hello.c", 163, 1627708787
	.dbg		file, "/Users/ryu/github/cc65/include/stdio.h", 6189, 1590551884
	.dbg		file, "/Users/ryu/github/cc65/include/stddef.h", 3057, 1590551884
	.dbg		file, "/Users/ryu/github/cc65/include/stdarg.h", 2913, 1590551884
	.dbg		file, "/Users/ryu/github/cc65/include/stdlib.h", 5999, 1590551884
	.forceimport	__STARTUP__
	.dbg		sym, "printf", "00", extern, "_printf"
	.dbg		sym, "text", "00", extern, "_text"
	.import		_printf
	.import		_text
	.export		_main

.segment	"RODATA"

L0003:
	.byte	$25,$73,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"

.segment	"CODE"

;
; printf ("%s\n", text);
;
	.dbg	line, "hello.c", 8
	lda     #<(L0003)
	ldx     #>(L0003)
	jsr     pushax
	lda     #<(_text)
	ldx     #>(_text)
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; return EXIT_SUCCESS;
;
	.dbg	line, "hello.c", 9
	ldx     #$00
	txa
;
; }
;
	.dbg	line, "hello.c", 10
	rts
	.dbg	line

.endproc

