;
; File generated by cc65 v 2.19 - Git 62da869e4
;
	.fopt		compiler,"cc65 v 2.19 - Git 62da869e4"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "hello.c", 214, 1628467924
	.dbg		file, "/home/pi/github/cc65/include/stdio.h", 5920, 1626994112
	.dbg		file, "/home/pi/github/cc65/include/stddef.h", 3057, 1626994112
	.dbg		file, "/home/pi/github/cc65/include/stdarg.h", 2913, 1626994112
	.dbg		file, "/home/pi/github/cc65/include/limits.h", 3580, 1626994112
	.dbg		file, "/home/pi/github/cc65/include/stdlib.h", 5999, 1626994112
	.forceimport	__STARTUP__
	.dbg		sym, "printf", "00", extern, "_printf"
	.dbg		sym, "text", "00", extern, "_text"
	.import		_printf
	.import		_text
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$25,$73,$20,$25,$64,$0A,$00
S0002	:=	S0001+5

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"
	.dbg	sym, "i", "00", auto, -2

.segment	"CODE"

;
; for(i=0;i<8;i++){
;
	.dbg	line, "hello.c", 9
	jsr     decsp2
	ldy     #$00
	tya
	sta     (sp),y
	iny
L0007:	sta     (sp),y
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cmp     #$08
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	bpl     L0003
;
; printf ("%s %d\n", text, i);
;
	.dbg	line, "hello.c", 10
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	lda     #<(_text)
	ldx     #>(_text)
	jsr     pushax
	ldy     #$07
	jsr     pushwysp
	ldy     #$06
	jsr     _printf
;
; for(i=0;i<8;i++){
;
	.dbg	line, "hello.c", 9
	ldy     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	iny
	lda     #$00
	adc     (sp),y
	jmp     L0007
;
; printf("\n");
;
	.dbg	line, "hello.c", 12
L0003:	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	ldy     #$02
	jsr     _printf
;
; return EXIT_SUCCESS;
;
	.dbg	line, "hello.c", 13
	ldx     #$00
	txa
;
; }
;
	.dbg	line, "hello.c", 14
	jmp     incsp2

	.dbg	line
.endproc

