;
; File generated by cc65 v 2.18 - Git f8be35b4
;
	.fopt		compiler,"cc65 v 2.18 - Git f8be35b4"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "hello.c", 214, 1628467608
	.dbg		file, "/Users/ryu/github/cc65/include/stdio.h", 6189, 1590551884
	.dbg		file, "/Users/ryu/github/cc65/include/stddef.h", 3057, 1590551884
	.dbg		file, "/Users/ryu/github/cc65/include/stdarg.h", 2913, 1590551884
	.dbg		file, "/Users/ryu/github/cc65/include/stdlib.h", 5999, 1590551884
	.forceimport	__STARTUP__
	.dbg		sym, "printf", "00", extern, "_printf"
	.dbg		sym, "text", "00", extern, "_text"
	.import		_printf
	.import		_text
	.export		_main

.segment	"RODATA"

L000D:
	.byte	$25,$73,$20,$25,$64,$0A,$00
L0012	:=	L000D+5

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"
	.dbg	sym, "i", "00", auto, -2

.segment	"CODE"

;
; for(i=0;i<8;i++){
;
	.dbg	line, "hello.c", 9
	jsr     decsp2
	ldy     #$00
	tya
	sta     (sp),y
	iny
	sta     (sp),y
L0002:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cmp     #$08
	txa
	sbc     #$00
	bvc     L0009
	eor     #$80
L0009:	bpl     L0003
;
; printf ("%s %d\n", text, i);
;
	.dbg	line, "hello.c", 10
	lda     #<(L000D)
	ldx     #>(L000D)
	jsr     pushax
	lda     #<(_text)
	ldx     #>(_text)
	jsr     pushax
	ldy     #$07
	jsr     pushwysp
	ldy     #$06
	jsr     _printf
;
; for(i=0;i<8;i++){
;
	.dbg	line, "hello.c", 9
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L000B
	inx
L000B:	jsr     stax0sp
	jmp     L0002
;
; printf("\n");
;
	.dbg	line, "hello.c", 12
L0003:	lda     #<(L0012)
	ldx     #>(L0012)
	jsr     pushax
	ldy     #$02
	jsr     _printf
;
; return EXIT_SUCCESS;
;
	.dbg	line, "hello.c", 13
	ldx     #$00
	txa
;
; }
;
	.dbg	line, "hello.c", 14
	jmp     incsp2
	.dbg	line

.endproc

